task: "brain-otock"
root_dir: "./data"

# experiment:
seed: 42
batch_size: 1
num_workers: 10
# model_name
model_name: "SegResnet_option1"
# loss

# dataset

## transform

max_epochs: 100
learning_rate: 1e-2s
use_scheduler: true

logs_dir: logs
checkpoint_dirpath: checkpoints
