task: "brain-otock"
root_dir: "./data"
device: "cuda"

experiment:
  seed: 42
  train_batch_size: 1
  valid_batch_size: 1
  num_workers: 10
  early_stopping_patient: 10

model_name: "SegResnet_option1"

dataset_name: "BratsDataset"

transform_name: "BratsTransform_base"

dataset_params:
  data_path: "./data"
  transform: null  # or specify the actual transform class or parameters here
  cache_rate: 0.5
  num_workers: 10

model_params:
  learning_rate: 1e-2
  max_epochs: 100
  use_scheduler: true

logs_dir: logs
checkpoint_dirpath: checkpoints
