task: "brain-sementic-segmentation"
device: "auto"
num_workers: 8
seed: 42
max_epochs: 200

experiment:
  train_batch_size: 6
  valid_batch_size: 3
  early_stopping_patient: 20


transform_name: "BratsAugmentation_base"
dataset_name: "BrainDataset"
dataset_params:
  data_path: "/player/data/BraTS2020_converted"
  cache_rate: 0.5
  num_workers: 8
  train_valid_test_split_rate: [0.7, 0.2, 0.1]

model_name: "SegResnet"
learning_rate: 1e-2
use_scheduler: true
model_params:
  blocks_down: [1, 2, 2, 4]
  blocks_up: [1, 1, 1]
  init_filters: 16
  in_channels: 4
  out_channels: 3
  dropout_prob: 0.2


logs_dir: logs
checkpoint_dirpath: checkpoints
ckpt_path: "/player/workspace/Python/brain-otock/checkpoints/run-2024-08-24-03-51-51/epoch=143-step=6192-val_loss=0.24-val_dice=0.724128.ckpt"
